### PR TITLE
for luasec params need fix

### PR DESCRIPTION
**Pull request by damody**
add protocol, certificate, key for handshake
for this samples can work
https://github.com/brunoos/luasec/tree/master/samples/verification/success

### CODE REVIEW

**Comment by damody** [comment]
add sleep in message_loop for cpu usage.
https://github.com/Yongke/luamqttc/pull/2/commits/62ef016068469a8b22a4c9e85c400f525f316bd0

**Comment by Yongke** [comment]
Hi, @damody 

Thanks for the fix. 

1. For ssl params, we are in ssl client mode, so luamqttc has two options a) verify the server certificate (verify = "peer") or b) just ignore it (verify = "none"). If a) is chosen, cafile need to be given(for example using https://curl.haxx.se/ca/cacert.pem)

so follow clips of code changed a little bit, 1) by default, luamqttc does not do the verify 2) if verify needed, pass the verify = "peer" and the cafile in connopts

And myself does not test scenario that server verifies the client, which you add. Did you try that?

```lua
    if connopts.usessl then
        local params = { mode = "client", protocol = "tlsv1_2", verify = "none" }

        if connopts.protocol then
            params.protocol = connopts.protocol
        end

        if connopts.verify then
            params.verify = connopts.verify
        end

        if connopts.cafile then
            params.cafile = connopts.cafile
        end

        if connopts.certificate then
            params.certificate = connopts.certificate
        end

        if connopts.key then
            params.key = connopts.key
        end

        sock = assert(ssl.wrap(sock, params))
        assert(sock:dohandshake())
        if params.verify == "peer" then
            assert(sock:getpeerverification())
        end
    end
```

2. for cpu usage, there's already a mechanism there, however the luasec need a small timer fix on this.
```lua
    -- in function _M.read_packet
    self.transport:settimeout(0.1)
    local data, err = self:receive(1)
```

**Comment by damody** [comment]
Hi @Yongke ,

thanks for your response.
1. Great!
2. On my machine, it doesn't work so I modify it.

**Comment by Yongke** [comment]
ok. I will merge it first and do the change we just discussed ;-)

**Pull request merged**
